ARG OSXCROSS_VERSION=latest
FROM --platform=$BUILDPLATFORM crazymax/osxcross:${OSXCROSS_VERSION}-ubuntu AS osxcross

FROM ubuntu:25.04
RUN apt-get update && apt-get install -y clang lld libc6-dev git autoconf wget make xz-utils cmake
ENV PATH="/osxcross/bin:$PATH"
ENV LD_LIBRARY_PATH="/osxcross/lib:$LD_LIBRARY_PATH"
RUN --mount=type=bind,from=osxcross,source=/osxcross,target=/osxcross
#Install flex for libpcap build
RUN cd /tmp/ && wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz && tar xvf flex-2.6.4.tar.gz && cd flex-2.6.4 && ./configure && make && make install
#Install bison for libpcap build
RUN cd /tmp/ && wget https://ftp.gnu.org/gnu/bison/bison-3.8.tar.xz && tar xvf bison-3.8.tar.xz && cd bison-3.8 && ./configure && make && make install
#Install libpcap for pcap++
RUN cd /tmp && git clone https://github.com/the-tcpdump-group/libpcap.git && cd libpcap && \
    ./autogen.sh && ./configure && make && make install
#Install pcap++
RUN cd /tmp/ && git clone https://github.com/seladb/PcapPlusPlus.git && cd PcapPlusPlus &&  \
        cmake -S . -B build && cmake --build build && cd build && cmake --install .
CMD ["/bin/bash"]